pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
				maven('clean package', 'java-tomcat-sample/pom.xml')
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Deploy in Staging Environment'){
            steps{
                build job: 'Deploy_Application_Staging_Env'

            }            
        }
    }
}